[TEAM 09] 인증을 제외한 기본 API 구현
codesquad-members-2021/baseball pull request #14
Opened 2021-05-07 12:45 UTC by isaac56

안녕하세요 백엔드 아이작입니다.

1주차까지 진행한 내용입니다.

## 1. DB 설계
 - Aggregate root를 크게 User, Team, Game 세 개로 나누어 설계해보았습니다.
 - Team은 Player를 갖고 있으며 여러 게임에서 재사용할 수 있도록 생각해 보았습니다.
 - Game은 진행중인 게임에 대한 정보를 갖고 있습니다.
 - Game Entity를 통하여 다음과 같은 테이블에 접근 가능합니다.
   - **batting_history**: 타자별 타율 기록)
   - **inning**: 각 이닝 별 (1회 초, 1회 말 등) 점수와 투구 기록을 갖고 있습니다.
     - Inning Entity를 통하여 pitch_history 테이블에 접근 가능합니다.
     - **pitch_history**: 어떤 투수가 어떤 타자에게 어떤 상황에서(예: 1 스트라이크 2볼인 상황) 어떤 투구(스트라이크, 볼)를 기록했는지 갖고 있습니다.
     
![](https://github.com/isaac56/baseball/blob/dev/BE/docs/database/Schema.png?raw=true)

## 2. 야구 게임의 진행을 서버에서 계산하는 방향으로 구현하였습니다.
- client는 서버에 세 가지의 결과(스트라이크, 볼, 안타) 만을 전송하고 서버는 전송받은 결과를 토대로 game 테이블을 수정합니다.
- Game entity를 통해 진행 상황에 필요한 모든 테이블에 접근 가능하기 때문에, Game entity 내부에 게임 진행에 필요한 대부분의 비즈니스 로직이 들어가있습니다.

## 3. 인증 기능을 제외한 상태에서 기본 API를 다음과 같이 구현하였습니다.
- API 문서 <https://documenter.getpostman.com/view/1562550/TzRRBTZ1>
- 게임방 목록 받기: GET /game/list
- 게임방 생성 요청: POST /game
- 게임방 참가 요청: POST /game/joining
- 게임 진행 (스트라이크, 볼, 안타) 요청: POST /game/status/pitch-result
- 게임 현황 요청(게임의 메인 뷰 업데이트): GET /game/status
- 이닝 별 스코어, 타율 기록 요청 (게임의 히스토리 뷰 업데이트): GET /game/history

## 4. AWS 배포하였습니다.
- baseball application을 위한 VPC를 생성했습니다.
- WAS용 인스턴스와 DB용 인스턴스를 나눠서 생성했습니다.
- WAS용 인스턴스는 public용 서브넷에 연결, DB는 private용 서브넷에 연결했습니다.

개발을 진행하면서 DB 설계 등 내용이 자주 변경되어 커밋 개수가 많은 점 양해부탁드립니다 ㅠㅠ
많은 지적 부탁드립니다.
항상 좋은 코드 리뷰 해주셔서 감사드립니다😁

2021-05-08 01:34 UTC, wheejuni requested changes
스펙이 꽤 방대하네요. 수고 많으셨습니다. 👍 
기본적으로 아래의 원칙은 항상 준수하셔야 합니다.

- Java의 네이밍 컨벤션은 camelCase 입니다. **항상 지키셔야 합니다.**
- `switch...case` 문은 사용을 최소화합니다. _다형성_ 으로 해결할 수 있습니다. 
- 클래스가 갖고 있는 필드가 5개 이상이라면, 클래스 분리 및 책임의 위임을 고민해볼 시점입니다.

이 세 가지 원칙만 제대로 가져가셔도...수정할 코드가 꽤 많다는 것이 느껴지실 겁니다. 
제가 코드 안에 남겨드린 피드백도 참고해 주시고, 앞으로의 설계 및 코드 구현에도 이 원칙을 항상 염두에 둬 주세요. 
감사합니다. 🥇

2021-05-08 01:34 UTC, wheejuni commented on BE/baseball/src/main/java/team9/baseball/DTO/request/CreateGameDTO.java
> +    private int home_team_id;
DTO라 하더라도 Java의 코딩 컨벤션을 항상 준수해 주시고요,
변수명을 카멜 케이스로 하더라도, DTO가 만들어낼 JSON의 필드명을 언더스코어 스타일로 내보낼 수 있는 설정 방식을 검색하고, 연구해 주시면 좋겠습니다.

**검색어**
- Spring Jackson Config
- Jackson annotation
- JsonProperty

2021-05-08 01:34 UTC, wheejuni commented on BE/baseball/src/main/java/team9/baseball/DTO/response/ApiResult.java
> +    private String error;
개인적인 생각이지만 `Error` 사유가 발생할 경우를 위한 다른 클래스를 만들어서 활용하는게 더 좋을 것 같아요.
`Exception` 과 상태 코드 매칭도 될 수 있도록요.
만약 정상적인 응답이 나갔다면 이 필드는 항상 `null` 일 것 같거든요, 그리 좋은 방법으로 보이지는 않습니다.

2021-05-08 01:34 UTC, wheejuni commented on BE/baseball/src/main/java/team9/baseball/DTO/response/BattingHistoryDTO.java
> +            hitRatio = (double) battingHistory.getHits() / (double) battingHistory.getAppear();
`BattingHistory` 에 위치할 로직이네요. `BattingHistory` 가 타율을 계산해주면 여기서 이렇게 로직을 전개할 필요가 없겠죠?

2021-05-08 01:34 UTC, wheejuni commented on BE/baseball/src/main/java/team9/baseball/DTO/response/GameHistoryDTO.java
> +        List<Integer> homeScores = acquireScores(game, Halves.BOTTOM);
`InningDto` 가 구성되어 있다면 아래 프라이빗 메소드에서 진행된 것처럼 복잡한 로직이 없어도 되지 않을까요?

2021-05-08 01:34 UTC, wheejuni commented on BE/baseball/src/main/java/team9/baseball/DTO/response/GameHistoryDTO.java
> +                game.getBatterUniformNumber() : game.getPitcherUniformNumber();
`Game` 에서 현재 플레이중인 타자와 투수 DTO를 만들어줄 책임을 수행해야 한다고 생각합니다.

2021-05-08 01:34 UTC, wheejuni commented on BE/baseball/src/main/java/team9/baseball/DTO/response/GameHistoryDTO.java
> +                .home_team(TeamHistoryDTO.of(homeTeam.getName(), homeScores, homeBattingHistories))
`.of()` 사용하신 것은 좋지만....사용해 보시니 어떤가요? 
생성자와 다른 점이 많이 느껴지시나요?
이럴때는 `Builder` 를 외부에 노출하고, 이런 곳에서도 `Builder` 사용하셔도 됩니다.

2021-05-08 01:34 UTC, wheejuni commented on BE/baseball/src/main/java/team9/baseball/DTO/response/GameHistoryDTO.java
> +                .filter(x -> x.getBatterTeamId() == team.getId())
`.get()` 으로 꺼내서 비교하는 것보다, `Team` 타입 파라메터를 받아 `boolean` 을 리턴하는 메소드가 구현되면 어떨까요?

```java
public boolean hasMatchingTeamId(Team team);

2021-05-08 01:34 UTC, wheejuni commented on BE/baseball/src/main/java/team9/baseball/DTO/response/GameStatusDTO.java
> +    }
`BattingHistory` 에 가 있어야 할 로직으로 생각되네요.

2021-05-08 01:34 UTC, wheejuni commented on BE/baseball/src/main/java/team9/baseball/DTO/response/GameStatusDTO.java
> +@Builder(access = AccessLevel.PRIVATE)
`Builder` 는 외부에 오픈되어도 됩니다.

2021-05-08 01:34 UTC, wheejuni commented on BE/baseball/src/main/java/team9/baseball/DTO/response/PlayerDTO.java
> +    public static PlayerDTO of(Team team, Integer uniform_number) {
`PlayerDTO` 는 있는데 `Player` 클래스는 없는 건가요?
`Player` 클래스를 원형 그대로 파라메터로 받으면, 좀 더 좋은 구현이 가능해질텐데요. 어떻게 생각하시나요.
예를 들어 지금 애매하게 `null check` 로 진행하고 있는 유니폼 번호 유효성 체크도 `Player` 단에서 처리할 수 있을 거고요.

2021-05-08 01:34 UTC, wheejuni commented on BE/baseball/src/main/java/team9/baseball/service/GameService.java
> +                break;
`Game.proceedBall()` 에 `pitchResult` 도 같이 넘어가면 스위치문을 없앨 수 있겠네요. 
그러면 어차피 `Game` 에 `switch` 문이 생기지 않냐고요? 그렇겠네요.
이걸 개선하려면 어떻게 해야 할까요?
`HIT, STRIKE, BALL` 에 각각 구분된 동작이 정의되어 있으면 되지 않을까요?
어떻게 정의하냐고요?
...

2021-05-09 13:04 UTC, isaac56 commented on BE/baseball/src/main/java/team9/baseball/DTO/request/CreateGameDTO.java
> +    private int home_team_id;
감사합니다 응답 시 DTO 변수명이 그대로 출력 되길래 큰 고민 없이 스네이크 케이스로 바꿔놨습니다.
찾아보니 카멜케이스를 json 반환시에만 스네이크케이스로 쉽게 변경할 수 있었네요!

2021-05-09 13:24 UTC, isaac56 commented on BE/baseball/src/main/java/team9/baseball/DTO/response/GameHistoryDTO.java
> +                .home_team(TeamHistoryDTO.of(homeTeam.getName(), homeScores, homeBattingHistories))
사실 저 부분에서 생성자로 생성하는 것과 큰 차이가 없어서 고민했습니다.
다른 DTO와 통일성을 주려고 of를 사용했었는데 그냥 builder를 노출해도 되겠군요

2021-05-09 14:36 UTC, isaac56 commented on BE/baseball/src/main/java/team9/baseball/DTO/response/GameHistoryDTO.java
> +        List<Integer> homeScores = acquireScores(game, Halves.BOTTOM);
inning 테이블은 이닝 별로 투구 결과와 점수를 저장하기 위해 만들었습니다.
아래의 프라이빗 메소드가 다소 복잡하기는 하지만, 
iOS 분들과 협의한 api 형태를 바꿀 만큼 InningDto를 만들어야 할지는 고민되네요😂
애초에 설계를 잘못한건지 score를 얻는 과정이 복잡한거 같기는 합니다
감사합니다

2021-05-09 15:01 UTC, isaac56 commented on BE/baseball/src/main/java/team9/baseball/DTO/response/PlayerDTO.java
> +    public static PlayerDTO of(Team team, Integer uniform_number) {
맞습니다 PlayerDTO인데 Player 클래스와 연관이 없는게 어색하네요 ㅠㅠ
현재 PlayerDTO에서 필요한 정보는 team id, name, uniform number 세가지입니다.

그리고 spring data jdbc에서 Team 객체가 Player 객체들을 맵으로 갖고 있고(OneToMany), 
player 테이블의 uniform_number를 맵의 key값으로 사용합니다.
이 때, Player 객체 내부에 uniformNumber를 선언하면 DB에서 조회시, uniform_number 칼럼을 중복으로 조회하더라구요.
(Team에서 Player 맵의 key값으로 uniform number를 갖기 때문에 한번 조회하고, Player가 uniformNumber를 갖고 있기 때문에 한번 조회 하는 것 같습니다)
```
SELECT ....., **uniform_number**, **uniform_number** FROM player WHERE ...
```

그렇다 보니 Player 객체에서 uniformNumber를 갖지 않게 했고, 따라서 uniform_number는 파라미터로 받아야 할 것 같습니다.

2021-05-09 15:20 UTC, isaac56 commented on BE/baseball/src/main/java/team9/baseball/DTO/response/PlayerDTO.java
> +    public static PlayerDTO of(Team team, Integer uniform_number) {
맞습니다 PlayerDTO인데 Player와 연관이 없다는게 이상하네요 ㅠ

말씀대로 고치는게 좋을 거 같은데 한가지 고민이 있습니다.

Team에서 Player들을 맵으로 갖고 있고(OneToMany), key값으로 player 테이블의 uniform_number를 사용하고 있습니다.
이 때, Player 객체에 uniformNumber 속성을 선언하면 uniform_number 칼럼을 중복해서 조회합니다.
(Team에서 Player 맵의 키값으로 uniform_number를 사용하기 때문에 한번, Player 객체에 uniformNumber가 선언되어 있어서 한번 조회하는것 같습니다.)
```
SELECT ....., uniform_number, uniform_number FROM player WHERE ...
```
따라서 Player 객체 내의 uniformNumber를 선언하지 않았고, 어차피 aggregate root가 Team이기 때문에 Team을 통해서만 Player에 접근할 수 있고, 따라서 uniform_number값은 Team의 playerMap의 키값으로만 접근하고 있었습니다.

PlayerDTO의 of 파라미터로 Player 하나만 받기 위해 그냥 Player 객체 내에 uniformNumber 값을 선언할지,
아니면 쿼리문에서 uniform_number를 두번 조회하지 않도록 Player 객체에 uniformNumber를 선언하지 않고 , PlayerDTO의 of 메소드에서 player와 uniformNumber를 파라미터로 받을지 고민입니다

2021-05-09 15:26 UTC, isaac56 commented on BE/baseball/src/main/java/team9/baseball/DTO/response/ApiResult.java
> +    private String error;
맞습니다 대부분 정상 응답일텐데 null을 항상 주는건 좋아보이지 않네요ㅠㅠ
지금 당장은 어떻게 바꿀수 있을지 떠오르지 않아서 천천히 고민해보겠습니다

2021-05-09 16:00 UTC, isaac56 commented on BE/baseball/src/main/java/team9/baseball/service/GameService.java
> +                break;
HIT, STRIKE, BALL 에 따라 변하는 상황이 다르기 때문에 코드 어딘가에서는 switch 또는 if 문으로 구분을 해야하지 않나요?
지금 제 수준으로는 조건식 없이 저 세가지 동작을 어떻게 구분해야 할지 떠오르지 않습니다 ㅠ

다형성을 이용하여 `HIT, STRIKE, BALL` 구분된 동작을 클래스로 정의해서 같은 interface를 구현하도록 해놓는다고 해도,
game 에서 사용할 구현체를 고를 때는 결국 조건식이 필요한게 아닌가요?

2021-05-09 16:07 UTC, isaac56 commented
제가 이해할 수 있는 부분은 반영했지만
어려워서 이해하지 못한 내용은 코멘트 남겨놨습니다.
조금만 더 설명해주시면 감사하겠습니다

코드 리뷰 감사드립니다😄

2021-05-09 16:39 UTC, isaac56 commented on BE/baseball/src/main/java/team9/baseball/DTO/response/PlayerDTO.java
> +    public static PlayerDTO of(Team team, Integer uniform_number) {
PlayerDTO인데 Player없이 생성하고 있었네요 😅
Player를 파라미터로 받아 생성하는게 PlayerDTO 입장에서 간결해지는 것 같습니다.

다만, 현재 API형태가 어떤 자리에 선수가 존재하지 않는다면 null을 반환하게 되어있습니다.
(1루에 주자가 없다면 Game 객체 내부의 `Integer base1UniformNumber` 값이 null이고, 마찬가지로 GameStatusDTO 내부의 `PlayerDTO base1` 값도 null을 반환해야 합니다.)
따라서, Player를 파라미터로 받을 경우 
1. PlayerDTO.of 메소드에서 파라미터 player가 null이면 null 반환
2. PlayerDTO.of를 호출할 때, 선수번호가 null이면 null을 넣고, null이 아니면 Player 인스턴스를 넣어야 함

이렇게 두 가지 과정이 필요해서 복잡해지기 때문에, 
Player없이 PlayerDTO를 생성하는게 어색하긴 하지만 기존 방식으로 복원했습니다.

2021-05-11 23:32 UTC, merged