[BE][NAS] 야구게임 API구현 및 OAuth로그인 기능 구현
codesquad-members-2021/baseball pull request #33
Opened 2021-05-13 11:03 UTC by Malloc72P

안녕하세요. 백엔드의 NAS라고 합니다
야구게임 기능구현 및 OAuth 적용을 완료해서 PR을 남기게 되었습니다.

# 야구게임 구현
* 야구는 테스트코드를 작성해가면서 기능구현을 했습니다
![image](https://user-images.githubusercontent.com/41663269/118095911-a91fb700-b40b-11eb-93c2-5e15b2f3d13f.png)

# OAuth 로그인 기능 구현
### 사용자 프로필정보 요청
* OAuth 로그인은 구글 OAuth를 통해 구현하였습니다
* 사용자가 로그인을 완료하고, Authorization Code가 CallbackURL에 매칭되는 컨트롤러 메서드로 넘어오면, 코드를 가지고 액세스 토큰을 요청하도록 구현했습니다
* 액세스 토큰을 획득하면, 토큰으로 사용자의 프로필 정보를 불러와서 디비에 저장하도록 구현했습니다.
### JWT 토큰 발급
* 사용자의 프로필 정보를 불러와서 저장한 다음에는 저희 서비스에 대한 액세스토큰과 리프래시 JWT토큰을 발급하도록 구현했습니다
* 아래와 같은 형태로 오도록 구현했습니다
![image](https://user-images.githubusercontent.com/41663269/118113637-7da7c700-b421-11eb-9551-c067d88de6f3.png)

### 토큰 리프래시
* 액세스토큰이 만료되면 리프래시 토큰으로 토큰 리프래시 요청을 해서 새로운 액세스 토큰과 리프래시 토큰을 받아오도록 구현했습니다
![image](https://user-images.githubusercontent.com/41663269/118113903-d5dec900-b421-11eb-96b0-27ecea3c99e8.png)

### 토큰 검사
* 토큰은 인터셉터를 이용해서 검사하도록 구현했습니다.
* `@Auth`어노테이션 유뮤를 가지고 검사할지 말지를 결정할 수 있도록 구현했습니다
```java
@Auth
@PatchMapping("/{gameId}")
public void joinIn(@PathVariable("gameId") int gameId, HttpServletRequest request) {/*...*/}
```

# 야구 게임 API
### 게임목록조회 API
![image](https://user-images.githubusercontent.com/41663269/118113983-f3139780-b421-11eb-9578-bc90e1a03f0f.png)

###  게임 참여하기 API
* 게임에 참여요청을 합니다
* Request Header의 Authorization에 담긴 액세스토큰을 가지고 어떤 사용자가 요청한건지 검사하도록 구현했습니다
![image](https://user-images.githubusercontent.com/41663269/118114118-21917280-b422-11eb-9dc2-78aa195a92b2.png)
* 만약 토큰이 유효하지 않으면 , 게임 참여하기는 실패하고, 다음과 같은 형식으로 응답해주도록 구현했습니다.
![image](https://user-images.githubusercontent.com/41663269/118114374-7503c080-b422-11eb-9321-afefd9c63e60.png)
* 또, 누군가에 의해 이미 선점된 게임이라면, 참여요청은 실패하고, 아래와 같은 응답을 받도록 구현했습니다
![image](https://user-images.githubusercontent.com/41663269/118114660-da57b180-b422-11eb-8187-962f37884846.png)

### 게임 상세조회 API
* 게임에 대한 세부정보를 조회합니다
* 해당 API도 토큰을 검증하도록 구현했습니다

### 피치하기 API
* 투수가 피치하게끔 요청하는 API입니다
* 해당 API도 마찬가지로 토큰검증을 하도록 구현했습니다.
* 추가로, 아무도 참여하지 않은 게임에다가 피치 요청을 하면 실패하도록 구현했습니다
![image](https://user-images.githubusercontent.com/41663269/118115011-5225dc00-b423-11eb-841b-316b16ade154.png)
* 또한, 다른 사용자가 선점한 게임에 피치요청을 하면 실패하도록 구현했습니다
![image](https://user-images.githubusercontent.com/41663269/118115052-64077f00-b423-11eb-975d-8a1c13097d91.png)
* 오직 자신이 선점한 게임에 한해서만 피치요청이 성공하게끔 구현했습니다
![image](https://user-images.githubusercontent.com/41663269/118115097-784b7c00-b423-11eb-904a-2584456ac48d.png)

# 배포
### 배포는 다음과 같은 구조로 했습니다
![image](https://user-images.githubusercontent.com/41663269/118116647-7be00280-b425-11eb-8c91-d7c99ad6f61e.png)

이상으로 글을 마치겠습니다.
이번 리뷰도 잘 부탁드립니다!

2021-05-13 13:34 UTC, ksundong commented
커밋되면 안되는 파일이 포함된 것 같습니다.
리뷰 받고자 하는 파일만 포함해서 PR 보내주세요!

2021-05-13 14:20 UTC, Malloc72P commented
헉, 문제 해결한다음에 다시 요청드리겠습니다!

2021-05-13 14:30 UTC, Malloc72P commented
해결했습니다!

2021-05-15 05:02 UTC, ksundong requested changes
안녕하세요! NAS! 리뷰어 Dion입니다.
야구게임은 상당히 어려웠던 프로젝트로 기억하고 있습니다. 어떤 기술을 선택할지도 되게 고민이 많이 되었던 것 같아요.
그래서 아마 제가 드리는 피드백이 어쩌면 너무 과할 수도 있다는 생각이 들어요.

이번 피드백은 전부 반영해주지 않으셔도 좋습니다. 왜냐하면 2주라는 기간이 짧기 때문에 아마 다 못하셨을거라고 생각되거든요.
제가 추천드리는 방법은, 일단 받은 피드백을 목록을 만드시고, 정리하신 다음 다음 미션에서 좀 더 개선된 형태로 진행하시는걸 추천드립니다.
되도록이면 매 주마다 PR을 보내셔서 지속적으로 피드백 받으시는걸 추천드려요.

## 피드백

- 클래스의 라인 수는 되도록이면 100줄 내외가 될 수 있도록 작성해보세요.
- Integeration Test와 Unit Test를 구분지어보시고, Unit Test를 중심으로 생각해봅시다.
- private 메서드의 개수보다는 뎁스가 3개 이상으로 늘어나지 않도록 클래스를 분리해봅시다. (최대한 2개까지)
- 코드는 코드를 읽는 사람과의 소통입니다. 처음 코드를 읽는 사람이 편할 수 있도록 코드를 작성해봅시다.
- 빌더 패턴은 만병통치약이 아닙니다. 필드가 많아진다면, 분리를 하는 것이 객체지향적인 사고라고 볼 수 있습니다.
- 예외 처리에 좀 더 신경써주세요.
- `HttpServletRequest`를 최대한 Controller에서 사용하지 않게끔 코딩해보세요.
- switch case문, else문을 최대한 피하는 방식으로 코딩해보세요.
- 코드블럭의 depth는 곧 그 코드블럭의 복잡도를 의미합니다. 뎁스를 최소화하는 방향으로 코딩해주세요.
- 도메인이 DTO를 아는 방식의 설계는 최대한 피해주시고, Converter 역할을 하는 DTO정도만 허용을 하는식으로 Domain이 DTO에 영향받지 않게끔 코딩해주세요.
- Builder 정도는 Lombok 사용을 추천드립니다. 다만 Builder가 남용되면 그건 그것대로 곤란합니다.
- 자바 컨벤션은 이제 리뷰 받으면 안됩니다. 습관화 해주세요!
- Optional의 사용이 필요한 경우와 그냥 null을 사용해도 되는 경우를 구분해보세요.
- IntStreamRange를 사용하는 것보다 for문을 사용하는게 더 나을 수도 있습니다.

2주간 프로젝트 수행하느라 고생많으셨고, 주말에 푹 쉬세요~!
궁금하시거나, 도움이 필요한 부분 이해가 가지 않는 부분등은 코멘트 남겨주시면 됩니다!

2021-05-15 05:02 UTC, ksundong commented on backend/build.gradle
> +	implementation 'io.jsonwebtoken:jjwt:0.9.1'
저는 auth0의 라이브러리가 더 낫더라고요~

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/annotation/Auth.java
> +public @interface Auth {
오호 어떤 용도의 애노테이션인지 문서화 해주면 더 좋았을 것 같아요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/config/AuthInterceptor.java
> +public class AuthInterceptor implements HandlerInterceptor {
인터셉터와 필터는 각각 어느 상황에서 사용해야 할까요?
이것도 제가 받았던 기술 면접 질문중에 하나입니다. 한 번 생각해보세요!

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/config/AuthInterceptor.java
> +    private final JwtVerifier jwtVerifier;
```suggestion
    private static final int TOKEN = 1;
    
    private final JwtVerifier jwtVerifier;
```

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/config/AuthInterceptor.java
> +    }
private 메서드는 사용되는 메서드 아래에 위치시켜주는 것이 가독성에 더 좋습니다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/config/AuthInterceptor.java
> +    }
또한 private 메서드가 너무 많이 등장한다면
별도의 클래스를 빼줘야하는 신호라고 보시면 좋을 것 같아요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/config/RefreshInterceptor.java
> +public class RefreshInterceptor implements HandlerInterceptor {
RefreshToken은 JWT 스펙은 아닙니다. OAuth 스펙이죠.
이것에 대해서도 공부해보시면 좋을 것 같네요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/config/RefreshInterceptor.java
> +    }
RefreshToken의 본질은 무엇일까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/config/WebMvcConfig.java
> +    }
https://eastglow.github.io/back-end/2019/08/01/Spring-Interceptor-사용-시-의존성-주입이-안되는-경우.html

interceptor도 bean으로 관리해보면 어떨까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/ExceptionController.java
> +    @ResponseStatus(HttpStatus.CONFLICT)
좋은 에러코드입니다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/ExceptionController.java
> +        return new ErrorDTO(HttpStatus.CONFLICT, exception.getMessage());
status를 리턴할 필요가 있나요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/ExceptionController.java
> +    @ExceptionHandler({PlayerNotFoundException.class, TeamNotFoundException.class, GameNotFoundException.class, UserNotFoundException.class})
그냥 NotFoundException으로 핸들링했으면 안될까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/ExceptionController.java
> +    public ErrorDTO handlePlayerNotFoundException(NotFoundException exception) {
메서드 명 확인해주세요!

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/ExceptionController.java
> +    public ErrorDTO handleInternalServerError(HttpRequestMethodNotSupportedException exception) {
여기도 메서드명 확인해주세요!

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/ExceptionController.java
> +    public ErrorDTO handleNoJwtTokenException(RuntimeException exception) {
둘을 묶는 다른 Exception을 선언해볼까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/ExceptionController.java
> +    }
👍

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/GameController.java
> +    @PatchMapping("/{gameId}")
왜 Patch를 써주셨는지 궁금해요.
이유가 있을 것 같거든요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/GameController.java
> +    public void joinIn(@PathVariable("gameId") int gameId, HttpServletRequest request) {
HttpServletRequest를 받지 않는 방식으로 개발하려면 어떻게 해야할까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/GameController.java
> +        String userId = ControllerUtil.extractUserIdFromRequest(request);
Util의 사용은 꼭 필요한 경우가 아니라면 지양해주세요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/GameController.java
> +    @Auth
모든 메서드에 붙이는 것은 비효율적이지 않을까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/UserController.java
> +    private final JwtBuilder jwtBuilder;
객체로 많이 분리가 되었군요!

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/UserController.java
> +    }
300번대 응답을 직접 주시면 어땠을까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/UserController.java
> +        UserInfoDTO userInfoDTO = googleApiRequester.requestUserInfo(receiveAccessTokenDTO.getAccess_token());
언더바가 등장했네요..?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +    private boolean isInitialized = false;
객체가 너무 큽니다.
적절한 단위로 분리하는게 좋을 것 같네요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +    public List<Map<TeamType, Integer>> showScoreBoard() {
Map이 아니라 객체의 List였다면 어떨까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +        }
승자를 결정하는 책임을 다른 객체에 넘겨주는게 어떨까 싶네요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +        }
switchCase를 쓰지않고, 로직을 전개시켜보세요.
PlayType이 해당 기능을 가지게 한다던가하는 식으로 바꿀 수 있어보입니다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +                defendingTeam().getCurrentPitcher(), attackingTeam().getCurrentHitter(), pitchResult.numberOfRunners());
한 번 다시 생각해보는게 좋을 것 같아요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +        }
이부분의 로직전개가 조금 아쉽네요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/PlayType.java
> +    AT_BAT
너무 종류가 다양하니 성격에 따라서 나눠주는게 좋아보입니다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +        return pitchResult;
depth수는 곧 복잡도입니다.
지금은 몇 depth죠?
이렇게 많은 조건문이 들어간다면, 다른 개발자는 어떻게 이해할 수 있을까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +        return pitchResult;
이 코드의 복잡도를 파악하는 아주 간단한 방법이 있습니다.
이 코드의 동작을 테스트 코드를 작성한다 가정하고 목록을 작성해보세요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +    private PitchResult judge4Ball() {
왜 숫자를 써주신건지 잘 모르겠어요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +        return pitchResult;
```suggestion
        }
        return pitchResult;
```

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +            pitchResult.addRunner(backHomeRunner);
되도록이면 상태를 변경하기 보다는 새로운 정보를 리턴하는 형태를 생각해봐주세요.
그러면 좀 더 간단한 코드가 작성됩니다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +        return backHomeRunners;
모든 주자가 돌아와야 하는 경우는 결국 새로운 상황에서 진행되는 것이라고 생각해보면 어떨까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +    }
int가 의미하는게 너무 추상적이어서, 별도의 객체가 있었으면 하네요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +    }
간소화해봅시다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +        }
각각을 변수로 추출하고 OR 조건으로 만들면 어떨까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +    }
연장 경기까지 설계한건 너무 어려움이 따랐을 것 같습니다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +}
이 클래스의 라인수는 610개고 메서드의 수는 엄청 많습니다.
이런 클래스는 책임도 너무많고 변경이 발생할 때, 헷갈릴 여지가 아주 많습니다.
꼭 개선해주세요. 다음 프로젝트에서 이런 클래스는 작성하지 않는것을 강력하게 권장하겠습니다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/inning/Inning.java
> +    private int game;
game은 무엇인데 int 타입이죠?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/inning/Inning.java
> +    }
이렇게 생성하면 inningNumber와 game은 0으로 초기화 될겁니다.
원하는게 그게 맞나요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/inning/Inning.java
> +        TeamType teamType = attackingTeam.getTeamType();
그냥 attackingTeam이 점수를 가지고 있으면, 그냥 그 팀의 점수를 올리면 될텐데요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/participant/PitcherPosition.java
> +    SP, RP, CP, NONE
NONE은 왜 필요한가요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/participant/PlayerParticipatingInGame.java
> +    }
비어있는 생성자를 선언해주신 이유가 있나요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/participant/PlayerParticipatingInGame.java
> +    private int team_participating_in_game;
자바 컨벤션을 지켜주세요...

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/participant/PlayerParticipatingInGame.java
> +    public float avg() {
줄여쓰기는 지양해주세요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/participant/PlayerParticipatingInGame.java
> +        return (float) hitCount / (float) plateAppearances;
둘 중 한 쪽만 형변환 해줘도 될텐데요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/participant/PlayerParticipatingInGame.java
> +public class PlayerParticipatingInGame {
어떤 용도의 클래스인지 잘 짐작이 안되네요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/participant/TeamParticipatingInGame.java
> +public class TeamParticipatingInGame {
이런것까지 도메인이어야 하나? 싶어요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/pitch/PitchResult.java
> +        }
잘 이해가 되지 않는 로직이네요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/team/Team.java
> +    private Set<Player> players = new HashSet<>();
Set을 사용해주신 이유가있나요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/team/TeamType.java
> +    NONE,
NONE팀은 무엇인가요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/user/User.java
> +    }
Domain이 DTO를 아는 방식의 설계는 지양해주세요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/user/User.java
> +    private String refreshToken;
필드를 적절히 책임별로 객체를 나눠보는건 어떨까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/user/User.java
> +    }
Update용 DTO를 별도로 선언해서 관리하는 것을 추천드릴게요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/user/User.java
> +    }
흔히 Converter라고 불리는 형태의 구현입니다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/dto/etc/ErrorDTO.java
> +    HttpStatus status;
접근제어자가 누락되었네요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/dto/etc/ErrorDTO.java
> +    HttpStatus status;
근데 HttpStatus는 왜 필드로 가지고 있나요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/dto/game/GameDTO.java
> +    public static class Builder {
빌더정도는 롬복을 써줘도 괜찮다고 생각해요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/dto/game/GameScoreDTO.java
> +                        .build())
빌더를 쓰지말고, 정적 팩토리 메서드를 사용해보시면 더 깔끔해질겁니다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/dto/oauth/JwtTokenDTO.java
> +    private Date refreshTokenExpirationDate;
각각을 객체로 만들어주면 어떨까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/dto/oauth/JwtTokenDTO.java
> +    private Date refreshTokenExpirationDate;
그리고 Java8의 날짜 시간 API를 사용해주세요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/dto/oauth/JwtTokenResponse.java
> +    }
이렇게 하면 token이 null인 상황이 발생할 수 있을 것 같은데요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/dto/oauth/ReceiveAccessTokenDTO.java
> +    private String id_token;
자바의 네이밍 컨벤션을 준수하는 형태로 변경해주세요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/dto/oauth/RequestAccessTokenDTO.java
> +    private String redirect_uri;
여기도 마찬가지로 네이밍 컨벤션 지켜주세요!

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/dto/oauth/ServerSecretDTO.java
> +    }
기본생성자만 세팅하면 나머지 필드는 어떻게 채워지나요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/dto/oauth/UserInfoDTO.java
> +
여기도 네이밍 컨벤션 지켜주세요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/exceptions/game/GameAlreadyOccupiedException.java
> +public class GameAlreadyOccupiedException extends NotFoundException {
NotFoundException하고 큰 연관이 없는 것 같은데요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/exceptions/game/GameIsNotStartedException.java
> +public class GameIsNotStartedException extends NotFoundException {
여기도 마찬가지로 NotFoundException하고는 큰 연관이 없어보입니다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/exceptions/notfound/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
예외 나누는걸 주저하지 마세요.
NotFoundException이 책임져야하는 범위만 책임져야 하는게 더 직관적이지 않을까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/exceptions/oauth/ExtractUserIdFromTokenFailedException.java
> +    public static final String EXTRACTION_FAILED = "인터셉터로부터 UserID를 전달받지 못했습니다";
메시지에 굳이 인터셉터라는 표현이 있어야 하는지 생각해보세요~

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/exceptions/oauth/InvalidJwtTokenException.java
> +    public static final String ILLEGAL_ARGUMENT_EXCEPTION = "아규먼트 형식이 잘못되었습니다";
👍

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/exceptions/oauth/InvalidRefreshTokenException.java
> +    public static final String INVALID_REFRESH_TOKEN = "사용자의 리프래시 토큰이 아닙니다";
유효하지 않은 리프레시 토큰이라는 내용이 더 정확하겠죠?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/DataInitializer.java
> +        });
그냥 for문 쓰셔도 됩니다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/GameService.java
> +    @Transactional(readOnly = true)
클래스 레벨에 readonly = true를 붙여주면 해당 클래스의 모든 메서드에 readonly가 적용됩니다.
필요한 부분에 Transactional 애노테이션을 붙여주면 좀 더 깔끔한 코드를 유지할 수 있습니다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/GameService.java
> +                }).collect(Collectors.toList());
Stream의 활용 좋습니다.
정적 팩토리 메서드 네이밍 컨벤션만 지켜주시면 좋을 것 같아요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/GameService.java
> +        }
이건 joinGame에서 발생시켜줘도 되겠죠?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/GameService.java
> +
사용되는 메서드 아래에 위치시켜주세요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/GameService.java
> +        }
else는 빼줘도 되겠죠?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/GameService.java
> +    }
일단 메서드명이 불필요하게 길다는 생각이 들어요.
그리고 private 메서드로 표현될만한 메서드도 아니라는 생각이 듭니다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/GameService.java
> +    }
여기도 private 메서드가 아닌 편이 낫겠네요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/GoogleApiRequester.java
> +        RequestAccessTokenDTO requestAccessTokenDTO = new RequestAccessTokenDTO(oAuthConfigManager.clientId(), oAuthConfigManager.clientSecret(), authorizationCode, REDIRECT_URI);
이런건 빌더 써주세요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/GoogleUrlService.java
> +    private final OAuthConfigManager oAuthConfigManager;
```suggestion
    private static final String GOOGLE_API_GET_LOGIN_PAGE = "https://accounts.google.com/o/oauth2/v2/auth";
    
    private final OAuthConfigManager oAuthConfigManager;
```

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/JwtBuilder.java
> +    }
각각이 다른 곳에서 만들어지는게 낫겠죠?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/JwtBuilder.java
> +    }
토큰을 Build 해주는 것도 따로 만들어봅시다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/JwtVerifier.java
> +    }
왜 user가 token을 verify할까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/JwtVerifier.java
> +    }
이 메서드도 사용되는 위치 아래에 위치시켜주세요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/OAuthConfigManager.java
> +            e.printStackTrace();
이거 말고 logger로 찍어봅시다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/OAuthConfigManager.java
> +            System.exit(1);
스프링 Application을 종료할 때는
https://stackoverflow.com/questions/22944144/programmatically-shut-down-spring-boot-application
이곳을 참고해서 종료시켜봅시다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/TeamService.java
> +    }
이런 편의 메서드가 왜 Service에 있는지 모르겠어요.
Player가 가지면 안될까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/OAuthConfigManager.java
> +            InputStream inputStream = OAuthConfigManager.class.getResourceAsStream("/server.secret.json");
try-with-resources 를 사용해주세요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/TestDataLoader.java
> +            InputStream inputStream = TestDataLoader.class.getResourceAsStream("/testData.json");
여기도 try-with-resources를 사용해주세요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/TestDataLoader.java
> +        HashMap<String, List<String>> testData = null;
왜 HashMap을 리턴해주시나요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/UserService.java
> +    }
이런 메서드가 필요할까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/UserService.java
> +        createUser(userInfoDTO, jwtTokenDTO);
private에서 public 메서드를 사용하면, public 메서드가 overriding되면 동작이 바뀔 우려가 있습니다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/UserService.java
> +        }
이곳 로직은 다시 구현해보시는게 좋을 것 같아요~

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/service/UserService.java
> +        }
Optional로 받을 이유가 전혀 없어보이는 코드입니다.
차라리 null체크를 직접 해주는게 좋을 것 같네요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/utils/ControllerUtil.java
> +    }
Spring에서 Custom Converter나 DataBinder를 구현하는 방법이 더 낫지 않을까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/utils/PitchRandomTable.java
> +    };
이렇게 많은 이유가 무엇인가요? 확률 때문인가요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/main/resources/application.properties
> +server.servlet.encoding.force=true
인코딩 설정이 왜 필요했나요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/test/java/com/codesquad/baseball/domain/TeamRepositoryTest.java
> +class TeamRepositoryTest {
Repository가 아닌 도메인 객체를 중점적으로 테스트 해보세요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/test/java/com/codesquad/baseball/domain/TeamRepositoryTest.java
> +        logger.debug("team : {}", team);
무엇이 테스트를 준비하기 위한 코드고
무엇이 테스트 대상인 코드인지 명확하지 않네요.
그리고 log를 찍어서 확인할 필요는 없는 것 같아요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/test/java/com/codesquad/baseball/domain/TeamRepositoryTest.java
> +            "TEST-PLAYER-C",
Integeration 테스트라면 좀 더 이름같은 이름으로 바꿔보시는걸 추천드릴게요.

2021-05-15 05:02 UTC, ksundong commented on backend/src/test/java/com/codesquad/baseball/domain/TeamRepositoryTest.java
> +            Player player = createHitter(playerNames[i], i + 3);
i + 3의 의미는 무엇인가요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/test/java/com/codesquad/baseball/domain/TeamRepositoryTest.java
> +        logger.debug("saved team : {}", team);
테스트 코드에서 로깅하는건 별 의미가 없다고 생각해요~

2021-05-15 05:02 UTC, ksundong commented on backend/src/test/java/com/codesquad/baseball/domain/GameRepositoryTest.java
> +    }
이것은 굳이 Spring Container가 없이도, 테스트 할 수 있는 단위테스트죠?
분리해봅시다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/test/java/com/codesquad/baseball/domain/GameRepositoryTest.java
> +    void testPitchIsBall() {
test라는 prefix는 굳이 없어도 되지 않을까요?

2021-05-15 05:02 UTC, ksundong commented on backend/src/test/java/com/codesquad/baseball/domain/GameRepositoryTest.java
> +        assertThat(game.homeTeamScore()).isEqualTo(2);
각각의 테스트를 분리해봅시다.

2021-05-15 05:02 UTC, ksundong commented on backend/src/test/java/com/codesquad/baseball/domain/GameRepositoryTest.java
> +    private void testHistoryOfCurrentInning(Game game) {
test코드가 너무 장황하죠?
좋은 테스트 코드는 한 눈에 알아볼 수 있어야 합니다.

2021-05-15 05:25 UTC, ksundong commented
> # 야구게임 구현
> * 야구는 테스트코드를 작성해가면서 기능구현을 했습니다
> * 그렇긴 한데, 아직 테스트코드를 작성하는게 많이 미숙한 듯 합니다
>   ![image](https://user-images.githubusercontent.com/41663269/118095911-a91fb700-b40b-11eb-93c2-5e15b2f3d13f.png)

제가 요청드린 테스트는 단위 테스트입니다. 아직 단위 테스트와 통합 테스트의 구분이 안되어 계신것 같아요.
단위테스트는 단위테스트 대로, 통합테스트는 통합테스트 대로 테스트 클래스를 구분지어주세요.
단위 테스트에서 주말에 한 번 공부해보시면 좋을 것 같네요.

> ### 어그리게이트
> * Game과 Team을 각각 분리된 어그리게이트로 만들었습니다.
> * Game을 어그리게이트 루트로 삼아서 게임에 관련된 모든 정보를 관리하도록 했습니다
> * Game과 별개로 팀 자체의 정보는 Team을 어그리게이트 루트로 삼아서 관리하도록 설계했습니다.
> * Game을 만들게되면 Team의 정보를 이용해서 팀이 게임에 참여했다는 정보를 저장하도록 했습니다.(TeamParticipatingInGame)
> * 이렇게 해서 게임마다 선수의 타순을 자유롭게 설정할 수 있도록 설계했습니다.

aggregate가 로직을 한 클래스(aggreate root)에 몰아두자가 아니라, endpoint를 root로 두자라고 생각하시면 좋을 것 같습니다.
각각의 aggregate는 여러 객체의 협력 구조로 이루어지는게 좋을 것 같습니다.

> ### 토큰 리프래시
> * 액세스토큰이 만료되면 리프래시 토큰으로 토큰 리프래시 요청을 해서 새로운 액세스 토큰과 리프래시 토큰을 받아오도록 구현했습니다
>   ![image](https://user-images.githubusercontent.com/41663269/118113903-d5dec900-b421-11eb-96b0-27ecea3c99e8.png)

리프레시 토큰은 JWT로 구현해주셔도 괜찮지만, 딱히 JWT를 쓸 이유도 없다고 생각합니다.
차라리 민감한 정보를 담아둘 수 있는 opaque token이라던가, cache server를 이용하는 방법도 있겠죠.
구현 방법은 여러가지지만, 나쁘지 않은 구현이라고 생각해요!

제가 회사에서 구현한 token 관련 로직은 access token을 요청할 때, access Token과 refresh Token을 발급해주고, refresh Token의 만료기간이 가까워 온다면, 만료시키고 새로운 refresh Token을 발급해주는 방식으로 구현했었습니다.

> ### 토큰 검사
> * 토큰은 인터셉터를 이용해서 검사하도록 구현했습니다.
> * `@Auth`어노테이션 유뮤를 가지고 검사할지 말지를 결정할 수 있도록 구현했습니다
> 
> ```java
> @Auth
> @PatchMapping("/{gameId}")
> public void joinIn(@PathVariable("gameId") int gameId, HttpServletRequest request) {/*...*/}
> ```

인터셉터가 적용될 path를 지정해주는 편이 좋지 않았을까 싶네요.


고생하셨습니다~

2021-05-15 07:18 UTC, Malloc72P commented on backend/build.gradle
> +	implementation 'io.jsonwebtoken:jjwt:0.9.1'
오 그러면 다음 프로젝트에서는 auth0를 써보면 좋을 것 같아요! 직접 경험해보고 어떤 차이가 있는지 배워보는것도 좋겠다는 생각이 드네요!

2021-05-15 07:28 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/annotation/Auth.java
> +public @interface Auth {
이럴 때 주석을 활용해서 애노테이션에 대한 문서화를 해도 될까요? 주석쓰면 좋을 것 같아요!

2021-05-15 07:31 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/config/AuthInterceptor.java
> +    }
구현에 너무 급급해서 하나의 클래스에 너무 많은 기능을 넣어버린 것 같아요... 분리해보겠습니다!

2021-05-15 07:44 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/config/RefreshInterceptor.java
> +public class RefreshInterceptor implements HandlerInterceptor {
로그인 기능 구현하면서 참 어려웠던게 이런 부분 같아요.
내가 하는 방법이 맞나? 하는 의문은 있는데, 찾아도 잘 안나오고 해서 어렵더라구요.

근데 이제보니 리프래시하는건 JWT쪽 이야기가 아니어서 그랬겠다는 생각이 드네요

그러면 한가지 궁금한게 있어요. 일단 제가 이해한 OAuth 로그인은 아래와 같습니다

1. 유저가 우리 서버한테 로그인 페이지를 요청
2. 우리 서버는 유저를 구글 로그인 페이지로 리다이렉션 시킴
3. 유저가 구글 로그인 페이지에서 로그인을 하고, 권한을 승인함
4. 3번에 대한 결과로 유저는 Authorization Code를 획득하고 CallBack URL로 리다이렉션됨
5. 우리 서버는 Authorization Code를 받아서 구글 인증서버에 AccessToken을 요청해서 획득함
6. 획득한 AccessToken을 가지고 유저의 프로필 정보를 요청해서 획득함
7. 여기까지해서 사용자 인증을 완료함.

저는 5번을 통해서 획득한 AccessToken은 유저의 프로필정보를 요청하는데만 쓰고 버린다고 생각했어요.
이걸 가지고 우리 서버에 대한 인증을 하면 위험하지 않을까 하는 생각때문이었어요.
그래서 따로 서버에 비밀키를 만들고, 이 키를 활용해서 JWT토큰을 만들었습니다.

제가 궁금한건, 이렇게 하는게 맞는지를 잘 모르겠어요. 
그냥 5번을 통해서 획득한 AccessToken을 써도 될까요?
아니면 제가 한대로 JWT토큰을 따로 만들어서 쓰는게 맞는걸까요?

그리고 이 경우에선 토큰 리프래시를 어떻게 하는게 좋을지를 잘 모르겠어요.
구글한테서 얻은 액세스토큰과 리프래시 토큰을 활용해서 하는건지, 아니면 제가 구현한 JWT 토큰 리프래시 방법도 괜찮은건지, 이걸 잘 모르겠네요. 아니면 이 질문에 대한 해답을 찾으려면 어떤걸 읽어보면 좋을까요?

2021-05-15 07:51 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/config/RefreshInterceptor.java
> +    }
보안을 강화하면서 사용자 경험을 최대한 해치지 않도록 도와주는 장치라고 생각해요

액세스토큰만 있으면 사용자 인증을 할 수 있으니까 노출되었을때 많이 위험할 것 같아요.
그래서 액세스토큰의 수명을 짧게 설정하는 것 같더라구요.

하지만 이렇게 하면 액세스토큰이 만료될때마다 사용자가 번거로운 로그인 작업을 반복해야 하니까 사용자 경험적인 측면에서는 좋지 않을 것 같아요.
그대신 리프래시 토큰을 적용하면 되는 것 같습니다. 액세스토큰보다 상대적으로 수명이 긴 리프래시 토큰을 발급하고, 이걸로 액세스토큰의 수명을 연장시킨다면 사용자가 매번 로그인작업을 반복하지 않아도 되니까 좋을 것 같아요.

그런데 생각해보니까 제 프로그램은 액세스토큰의 만료여부와 관계없이 리프래시토큰으로 리프래시 요청만하면 새로운 토큰을 발급해주네요? 음... 액세스토큰이 만료되었는지도 검사해줘야 할 것 같아요.

근데 이것도 맞는 설계인지 잘 모르겠어요... 위에서 언급하신 내용처럼, 토큰 리프래시는 JWT의 스펙이 아니니까, 이런 방식의 구현은 JWT토큰의 설계의도와 맞지 않는다는 생각이 드네요...

2021-05-15 07:53 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/config/WebMvcConfig.java
> +    }
와... 이게 되네요...... 꿀팁 정말 감사합니다!

2021-05-15 07:56 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/controller/ExceptionController.java
> +        return new ErrorDTO(HttpStatus.CONFLICT, exception.getMessage());
아 이부분은 사이드디쉬 프로젝트를 진행할때 모바일 팀원분이 바디로 상태코드도 주면 좋겠다고 하신게 생각이 나서 반영했던 부분이예요. 제가 모바일이랑 리엑트쪽 상황을 잘 몰라서 일단 넣어주도록 했습니다.

2021-05-15 07:57 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/controller/ExceptionController.java
> +    @ExceptionHandler({PlayerNotFoundException.class, TeamNotFoundException.class, GameNotFoundException.class, UserNotFoundException.class})
오... 저거 설마 `{A.class, B.class, C.class}`이렇게 안해도 되는거예요?
몰랐어요... 꿀팁 감사합니다! 한번 해보고 다시 코멘드 달겠습니다!

2021-05-15 07:58 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/controller/ExceptionController.java
> +    public ErrorDTO handlePlayerNotFoundException(NotFoundException exception) {
으악 실수했네요!

2021-05-15 07:58 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/controller/ExceptionController.java
> +    public ErrorDTO handleNoJwtTokenException(RuntimeException exception) {
NotFoundException처럼 상위 클래스를 하나 만들어주면 그룹화해서 관리할 수 있겠네요!

2021-05-15 08:25 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/controller/GameController.java
> +    @PatchMapping("/{gameId}")
아, 이 부분은 Put이랑 Patch중에서 고민하다가 Patch를 선택했어요.

제가 이해한 Patch와 Put메서드는 아래와 같습니다
- Put은 타겟이 되는 리소스가 없으면 보낸 데이터대로 생성하고, 있으면 교체하는식의 수정요청을 할때 사용
- Patch는 리소스에 대한 부분적인 수정을 요청할때 사용

이렇게 생각해봤을 때, 해당 컨트롤러 메서드는 게임의 선점상태값만 부분수정하는 기능이니까 Patch가 맞겠다는 생각을 했습니다. 또, 대상 게임이 없을때 게임을 생성한다던가 하는 기능도 없으니까 더더욱 Put을 쓰면 안되지 않을까? 하는 생각이 들더라구요.

2021-05-15 08:28 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/controller/GameController.java
> +    public void joinIn(@PathVariable("gameId") int gameId, HttpServletRequest request) {
아, 이부분도 엄청 고민하던 부분 중 하나예요.
저도 `HttpServletRequest`말고 다른게 없을까? 해서 이것저것 시도도 해보고 구글링도 해봤는데...
결국 이것말고는 못찾았어요...

여기서 관건은 인터셉터에서 컨트롤러 메서드로 값을 넘겨주는 중간 개체가 있거나 하면 좋겠는데, HttpServletRequest말고는 잘 모르겠더라구요....

근데 지금 다시보니까 인터셉터에서 handler를 받잖아요? 이거가지고 어떻게 해볼 수 없을까? 라는 생각이 드네요.
한번 도전해보고 다시 코멘트 남기겠습니다!

2021-05-15 08:30 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/controller/GameController.java
> +        String userId = ControllerUtil.extractUserIdFromRequest(request);
앗 이부분은 중복코드를 줄이려는 목적으로 사용한건데요, 그러면 이런 경우에는 어떤 방법을 사용하는게 좋을까요?

유틸 사용을 피한다면, 서비스로 만들어보는것도 좋을 것 같아요!

2021-05-15 08:33 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/controller/GameController.java
> +    @Auth
오... 이 부분도 코드 중복이 되겠네요...
이 부분은 WebMvcConfigure에서 설정을 좀 더 잘해주면 `@Auth`를 안붙이고도 해결할 수 있을 것 같아요.
한번 도전해보겠습니다!

2021-05-15 08:34 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/controller/UserController.java
> +    private final JwtBuilder jwtBuilder;
저번 사이드디쉬 프로젝트에서 가져와서 조금 고쳐봤습니다!  이정도면 잘 분리한거 맞죠? 😄

2021-05-15 08:36 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/controller/UserController.java
> +    }
아하 [여기 내용처럼](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/304) 304로 응답을 주는편이 더 좋겠네요!
`캐시된 자원으로의 암묵적인 리다이렉션이다`라는걸 상태코드를 가지고 표현할 수 있어서 이렇게 해야겠네요!
알려주셔서 감사합니다!

2021-05-15 08:39 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/controller/UserController.java
> +        UserInfoDTO userInfoDTO = googleApiRequester.requestUserInfo(receiveAccessTokenDTO.getAccess_token());
앗, 이거 저번 사이드디쉬때 달아주신 리뷰인데 깜빡하고 못고쳤네요... 정말 죄송합니다 ㅠㅠ

약간 변명을 하자면 구글에서는 스네이크 케이스로 응답을 주더라구요. 여기에 맞추느라고 스네이크 케이스로 했던건데, 보니까 백엔드 동료인 코코가 이런것도 설정을 잘 하면 Jackson에서 스네이크케이스로 온 json을 카멜케이스로 잘 바꿔준다고 했던게 기억나네요. 카멜케이스로 바꿔도 잘 돌아갈 수 있도록 고쳐봐야겠네요

2021-05-15 08:45 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +    private boolean isInitialized = false;
맞아요 이거 코드 짜면서도 너무 커서 분리하고 싶었는데 방법이 떠오르지 않아서 그냥 했던 기억이 나요.

조금 시간이 지나서 보니까, 게임 객체를 이렇게 분리하면 어떨까 하는 생각이 드네요

```
Game
  |______ TeamData(팀 정보관리)
  |______ Diamond(1,2,3루랑 마운드, 타석 상태정보 관리)
  |______ DashBoard(이닝정보 및 점수관리)
```
하 근데 이거 또 걱정이 되는게 SpringDataJDBC를 쓰다보니까 설정하나 잘못건들면 막 안되고 그러니까 객체분리하는게 엄청 겁나네요 ㅋㅋㅋㅋ
그래도 한번 해보고 싶네요. 도전해보겠습니다

2021-05-15 08:49 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +    public List<Map<TeamType, Integer>> showScoreBoard() {
아 이 부분을 Map으로 한 이유는, 팀이 홈인지 원정팀인지 여부를 표현하기 위해서였어요.

그랬긴한데, 이거 그냥 제가 야구 규칙을 잘 몰라서 이렇게 한 거였더라구요 😄 

이거 점수판에서 위가 away이고 아래가 home인 것 같더라구요. 그러면 그냥 List로 표현해서 0번째를 away, 1번째를 home으로 하는편이  좀 더 야구규칙에 맞겠다는 생각이 드네요 😄 

이게 다 야구를 게임으로만 하고 직접 본 적이 없어서 그런 것 같습니다 ㅎㅎㅎㅎ 너무 어릴때 했던거라 기억이 잘 안나네요

2021-05-15 08:51 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +        }
오, 이것도 객체분리할때 적용해보면 좋겠네요.

그러면 경기판정하는 로직을 분리해볼 수 있겠어요!

2021-05-15 08:56 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +        }
오 그러면 `playType.play()` 이런식으로 하면 스위치 케이스문이 한줄짜리 코드가 될 수 있겠군요!

근데 저기있는 onStrike, onBall같은 메서드들은 Game의 상태값을 바꾸는 메서드인데, 저게 PlayType으로 넘어가면 PlayType에서 외부의 객체인 Game의 상태값을 바꾸는게 되버려서 위험해질 것 같아요. 아니면 다른 방법이 있을까요?

야구 로직처리하는 부분이 많은 아쉬움이 남네요... 처음에는 대충 이렇게 하면 되지 않을까 해서 했던건데, 전체설계를 하지 않고 무작정 덤빈 대가를 톡톡히 치른 것 같네요...

2021-05-15 08:58 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +                defendingTeam().getCurrentPitcher(), attackingTeam().getCurrentHitter(), pitchResult.numberOfRunners());
속성값대신 객체를 넘기는편이 더 좋았을까요?
메서드를 만들때, 어떨때는 속성을 넘기고, 어떨때는 객체를 넘겨야 할지가 잘 감이 안잡히네요.
좀 더 고민해보겠습니다!
혹시 좋은 팁이 있다면 알려주세요!

2021-05-15 09:22 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +        }
처음부터 야구게임 로직을 어떻게 구현할지 잘 설계하고 들어갔어야 하는데, 그렇게 안하고 무작정 덤빈 대가를 치르고 있는 것 같네요 ㅠㅠ
맞아요 저게 요구사항 분석을 완벽하게 안하고 짜다보니까, 나중으로 가면 갈수록 코드 수정이 많이 발생하더라구요.
그러면서 이해하기도 어렵고, 복잡하고 난해한 코드가 되어버린 것 같네요... 반성하겠습니다

2021-05-15 09:24 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/domain/game/PlayType.java
> +    AT_BAT
별도로 OutType같은걸 만들면 어땠을까 하는 생각이 드네요. 확실히 PlayType이라고 보기엔 어려운 값들이 많이 있네요

2021-05-15 09:29 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +        return pitchResult;
에고고... 너무 배려없는 코드였군요... 조심하도록 하겠습니다

너무 많이 깊어진체로 코드를 작성해놓으니까 제가 짰는데도 보기가 어렵네요
이런 방식의 코드작성은 최대한 피하도록 하겠습니다

2021-05-15 09:30 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +    private PitchResult judge4Ball() {
볼넷상황에 대한 판정을 하는 메서드라서, 볼넷을 표현하려고 4를 작성했어요

2021-05-15 11:53 UTC, Malloc72P commented
오우 디온... 정말 세심한 리뷰 감사드려요!

오늘안에 다 반영해보려고 했는데 힘들 것 같네요

내일 이어서 더 해보겠습니다

2021-05-16 06:55 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/config/AuthInterceptor.java
> +public class AuthInterceptor implements HandlerInterceptor {
이번 기회를 이용해서 필터와 인터셉터에 대해 조금 공부해보고 정리해봤어요!
https://www.notion.so/Filter-Interceptor-AOP-37b1dd207abc4b91a8424f0eaca65ee1

필터와 인터셉터 둘 다 컨트롤러의 핸들러 메서드의 앞과 뒤에서 호출될 수 있지만, 구조상 필터가 인터셉터보다 먼저 요청을 받아서 필터링 할 수 있다는 성질을 숙지하고 써먹으면 좋을 것 같더라구요.

그런데 한가지 잘 모르겠는점이 생겼네요
토큰인증과 같은 일은 어디서 처리하는게 좋을까요?
찾아보니까 필터에서도 충분히 토큰인증관련 로직을 처리할 수 있겠더라구요.
그러면 필터랑 인터셉터 둘 다 토큰인증처리 로직을 처리할 수 있다면, 이 일을 더 잘할 수 있는 객체한테 맡기는게 좋겠는데, 이 판단을 하기 위한 조건에 어떤게 있을지 잘 모르겠어요.

우선 제 생각에는 인터셉터에서 하는편이 좋지 않을까 싶어요. 제가 이해한게 맞다면, 인터셉터도 DispatcherServlet의 ApplicationContext안에 있는 Bean이고, 그러면 여기서 예외가 발생하더라도 ControllerAdvice를 통해서 핸들링 할 수 있으니까 좀 더 편하게 구현할 수 있지 않을까 라는 생각이 들었기 때문이예요.
그러면 필터는 어떨까 싶긴 한데, 지금까지 프로젝트를 하면서 필터를 활용해본적이 없어서 잘 모르겠네요 ㅋㅋ
다음 프로젝트에서 실험적으로 필터를 사용해보면 좋겠다는 생각이 듭니다. 직접 경험해보고 어떤 불편함이 있는지, 아니면 어떤 장점이 있는지 직접 겪어봐야겠습니다

2021-05-16 07:45 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/controller/GameController.java
> +    public void joinIn(@PathVariable("gameId") int gameId, HttpServletRequest request) {
좀 더 찾아봤는데 도저히 모르겠어요......
인터셉터에서 컨트롤러의 핸들러메서드로 토큰에서 꺼낸 UserID를 넘겨주고 싶은데, handler는 값을 담아서 갈 수 있는 객체가 아닌 것 같더라구요...
아니면 이런 방식의 구조는 피해야하는걸까요?

인터셉터에서 핸들러로 값을 넘기는걸 피해야 한다면, 핸들러 메서드에서 request의 헤더에 있는 토큰을 꺼내서 해독하고 userId를 꺼내는 일을 다시 수행해야할 것 같은데, 인터셉터에서 이미 수행한 동작을 또 하는것도 별로 좋은 방법은 아닌 것 같아요.

그러면 생각나는게 request랑 response말고는 없는데, 혹시 힌트 주실 수 없을까요?

2021-05-16 08:12 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/controller/UserController.java
> +        UserInfoDTO userInfoDTO = googleApiRequester.requestUserInfo(receiveAccessTokenDTO.getAccess_token());
```java
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public class ReceiveAccessTokenDTO {

    private String accessToken;
    private int expiresIn;
    private String scope;
    private String tokenType;
    private String idToken;
}
```
JsonNaming애노테이션으로 해결했습니다!

2021-05-16 08:18 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +        return backHomeRunners;
그것도 좋은 방법일 것 같아요!

일단 위의 코드는 클라이언트한테 홈에 들어온 주자들의 타순과 들어온 순서까지 주고 싶어서 저렇게 구현하게 되었습니다.

2021-05-16 08:26 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/domain/game/inning/Inning.java
> +    private int game;
game에 대한 id입니다

DataJdbc에서 OneToMany관계로 할때, 스키마로 상위 어그리게이트에 대한 fk의 이름을 테이블로 쓰더라구요.
바꾸면 game말고 다른걸로 쓸 수 있긴 한데 그러지 않고 그냥 쓴것으로 보입니다
다음부터는 MappedCollection을 사용해서 좀 더 명확한 이름을 주도록 하겠습니다. game보다는 gameId가 더 좋겠네요

2021-05-16 08:35 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/config/WebMvcConfig.java
> +    }
그런데 이렇게하면 인터셉터에서는 생성자주입을 못쓰게 되는건가요?

그러면 WebMvcConfigurer에서 직접 인터셉터의 생성자에 서비스를 주입하는 방법이 더 좋지 않을까 하는 생각이 들어요

2021-05-16 10:06 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/GameController.java
> +    public void joinIn(@PathVariable("gameId") int gameId, HttpServletRequest request) {
https://github.com/ksundong/simple-spring-param-resolver
여길 참고해보세요.

2021-05-16 14:16 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/config/WebMvcConfig.java
> +    }
음 근데 좀 더 고민해보니까 생성자 주입으로 하면 WebMvcConfig에서 매번 번거롭게 주입해줘야 하네요...
그냥 인터셉터도 빈으로 관리해서 Resource애너테이션으로 의존성을 주입하는게 더 좋을 것 같아요!

2021-05-16 14:37 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/controller/GameController.java
> +    public void joinIn(@PathVariable("gameId") int gameId, HttpServletRequest request) {
와 제가 지금까지 아무생각없이 쓰고있던 `@PathVariable`이 디온이 알려주신 ArgumentResolver를 통해서 이루어지는거였군요... 배운 내용을 노션에 정리해보았습니다
https://www.notion.so/HandlerMethodArgumentResolver-5ebd3295d13349d2a0548d96f73a8054

baseball프로젝트에도 적용해봤어요! 
디온이 컨트롤러의 핸들러메서드에서 `HttpServletRequest`를 안받고 구현하라고  말씀하신 이유를 조금은 알 것 같아요.
어떻게 보면 `PathVariable`도 이거랑 같은 맥락이 아닐까 싶어요. url에서 pathVariable을 얻고자 한다면, 직접 HttpServletRequest를 받아서 처리하는 방법도 있겠죠. 하지만 이런식으로 request에서 무언가를 꺼내는 일이 많아진다면, 컨트롤러에서 이걸 꺼내는 메서드를 호출하는것도 불필요한 작업이 되겠다는 생각이 드네요. 그냥 ArgumentResolver를 쓰면 해결되는 문제니까요.

알려주셔서 정말 감사합니다!

2021-05-16 14:44 UTC, Malloc72P commented
주말내에 리뷰해주신 내용을 다 공부해보고 반영해보려고 했는데요, 생각처럼 잘 안되네요 ㅠㅠ

다음주가 되면 새 프로젝트가 시작돼서 많이 바쁘겠지만, 짬짬히 시간내서 공부하고 반영할께요!

2021-05-16 16:45 UTC, ksundong commented on backend/build.gradle
> +	implementation 'io.jsonwebtoken:jjwt:0.9.1'
좋은 태도네요 👍

2021-05-16 16:45 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/annotation/Auth.java
> +public @interface Auth {
JavaDoc은 주석이라고 보기 어려울 정도로 좋은 기술입니다. 적극적으로 써먹어보셔도 좋을 것 같아요.

2021-05-16 16:47 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/config/AuthInterceptor.java
> +public class AuthInterceptor implements HandlerInterceptor {
제일 중요한게 빠졌네요.
Filter는 Servlet의 스펙이고, Interceptor는 Spring의 스펙입니다.
https://goddaehee.tistory.com/154
이 글도 한 번 참고해보세요.

2021-05-16 16:50 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/config/AuthInterceptor.java
> +public class AuthInterceptor implements HandlerInterceptor {
인증이 Spring의 도움이 필요한 경우 Interceptor일 것이고, 그게 필요없다면 Filter의 영역이겠죠?
더 나아가서, Spring Security를 사용한다면 그런 고민도 깔끔하게 해소시킬 수 있고요.
필터에서도 얼마든지 ControllerAdvice로 Handling 할 수 있기 때문에 말씀하신 이유로 선택하는건 조금 곤란할 것 같아요.
한 번 직접 필터를 사용해보세요~

2021-05-16 16:52 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/config/RefreshInterceptor.java
> +public class RefreshInterceptor implements HandlerInterceptor {
잘 생각해봅시다. 구글에서 준 AccessToken은 어떤 AcessToken일까요?
우리가 발급해 준 JWT Token은 어떤 AccessToken일까요?

---

토큰 리프레시는 OAuth 스펙이라고 말씀드린 부분인데, 잘 생각해보세요.
토큰 리프레시 하는 방법은 찾아보시면 꽤 나올거에요. 다만 저는 리프레시 토큰을 위해 JWT를 쓰는건 바람직하지 않다고 생각해서 회사에 구현한 리프레시 로직은 UUID + Cache Server로 구현되어 있습니다.
질문에 대한 답은 여러개이기 때문에 많은 생각 혹은 경험을 해보시길 추천드려요.

2021-05-16 16:56 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/config/RefreshInterceptor.java
> +    }
해당 리프레시 토큰은 그럼 노출이 안될까요?
리프레시 토큰을 가지고 액세스 토큰의 갱신 요청만 해도 말씀하신 위험이 발생할텐데요!
GitHub같은 경우에는 Opaque Token을 사용하고, Refresh Token을 발급하지 않습니다.
왤까요? 저도 생각해보지 않은 문제인데, 한 번 생각해보시면 좋을 것 같네요.

2021-05-16 16:57 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/config/WebMvcConfig.java
> +    }
생성자 주입은 됩니다.
아직 스프링을 잘 이해하지 못하신게 아닐까 하는 생각도 드는군요.

2021-05-16 16:58 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/ExceptionController.java
> +        return new ErrorDTO(HttpStatus.CONFLICT, exception.getMessage());
원래라면 필요 없어야 합니다. ㅎㅎ

2021-05-16 16:58 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/ExceptionController.java
> +    @ExceptionHandler({PlayerNotFoundException.class, TeamNotFoundException.class, GameNotFoundException.class, UserNotFoundException.class})
기다리고 있겠습니다. ㅎㅎ

2021-05-16 16:59 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/GameController.java
> +    @PatchMapping("/{gameId}")
네 Patch는 Partial Update를 의미하는게 맞습니다.
잘 이해하고 계시네요. 😊

2021-05-16 17:02 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/GameController.java
> +    public void joinIn(@PathVariable("gameId") int gameId, HttpServletRequest request) {
PathVariable의 원리는 저도 잘 모르겠네요. 비슷한 로직이겠죠 ㅎㅎ
저도 이론만 알고 실제로 구현하는데 한 시간 정도 걸렸는데, 도움이 되었으면 좋겠네요.

2021-05-16 17:04 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/controller/GameController.java
> +        String userId = ControllerUtil.extractUserIdFromRequest(request);
네 맞습니다. 객체지향적인 사고를 유도하기 위함입니다.
적절한 사용은 말리지 않습니다만, 먼저 Util을 생각하지말고, Service 내지는 Component로 객체가 그 일을 담당하게 끔 생각해봐주세요.
그리고, 이제는 필요없어진 코드리라 생각됩니다. 😊

2021-05-16 17:05 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +        }
상태값을 바꾸지 않고, 상태값을 새로 지정해서 리턴하는 방식도 있겠죠~

2021-05-16 17:06 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +                defendingTeam().getCurrentPitcher(), attackingTeam().getCurrentHitter(), pitchResult.numberOfRunners());
History Builder를 써서 history를 만든다음, history를 넣어줘도 좋을 것 같네요.

2021-05-16 17:06 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +                defendingTeam().getCurrentPitcher(), attackingTeam().getCurrentHitter(), pitchResult.numberOfRunners());
그냥 파라미터가 3개 이상이다 싶으면, 객체로 묶거나 빌더를 쓰는 편이에요.

2021-05-16 17:07 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/domain/game/Game.java
> +    private PitchResult judge4Ball() {
이게 자바나 프로그래밍 진영에서 4는 for를 의미하는 경우가 많아서 불필요하게 숫자를 쓰기보다는 Four라고 써주는게 더 좋아보여요.

2021-05-16 17:15 UTC, ksundong approved these changes
마지막 리뷰입니다.
주말에 피드백 적용하느라 고생하셨어요~

2021-05-16 17:15 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/config/interceptor/RefreshInterceptor.java
> +    @Resource
리소스 애노테이션도 그리 좋은 선택은 아닙니다.
`@Autowired`랑 다를게 크게 없어요.

2021-05-16 17:15 UTC, ksundong commented on backend/src/main/java/com/codesquad/baseball/config/interceptor/RefreshInterceptor.java
> +        request.setAttribute(CERTIFIED_USER, certifiedUser);
자, 잘 생각해봅시다. User를 리턴해주면, 우리가 지금까지 설정했던 관계들이 전부 꼬이게 되지 않나요?
Controller가 도메인을 알게될겁니다. 별로 좋지 못하겠죠?

2021-05-16 17:15 UTC, merged

2021-05-19 13:09 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/config/interceptor/RefreshInterceptor.java
> +    @Resource
위에서 말씀해주신 것처럼 스프링 공부를 더해보고 생성자주입으로 넣을 수 있도록 고쳐보겠습니다!

2021-05-19 13:10 UTC, Malloc72P commented on backend/src/main/java/com/codesquad/baseball/config/interceptor/RefreshInterceptor.java
> +        request.setAttribute(CERTIFIED_USER, certifiedUser);
그러네요... 인터셉터도 그렇고, 디온이 말씀해주신대로 컨트롤러에서 유저를 알게되버리니까 의도치않은 의존관계가 생겨버리는군요... 기존에 하던대로 토큰에서 userId만 추출해서 넘겨주는 편이 더 나았겠네요